# build containers with
#docker compose up -d --build

# take down with (-v takes down volumes)
#docker compose down -v

# restart all running containers
#docker compose restart

# check status with
#docker compose ps

# read logs for <container-name> with
#docker logs <container-name>

# to make the current terminal open in <container-name>
#docker exec -it <container-name> /bin/bash

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/app/results
      - ./logs:/app/logs